# Generated by Django 5.2.8 on 2025-12-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
    ]
