# Generated by Django 5.2.8 on 2025-12-10 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_last_login_date_customuser_streak_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='xp_reward',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='notification_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(choices=[('uploads', 'Number of uploads'), ('likes_given', 'Number of likes given'), ('likes_received', 'Number of likes received'), ('level', 'User level'), ('comments', 'Number of comments'), ('followers', 'Number of followers')], max_length=50),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
