services:
  - type: web
    name: stars-project
    env: python
    region: oregon
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: "3.13"
      - key: SECRET_KEY
        fromEnv: SECRET_KEY
      - key: DATABASE_URL
        fromEnv: DATABASE_URL
      - key: SUPABASE_URL
        fromEnv: SUPABASE_URL
      - key: SUPABASE_KEY
        fromEnv: SUPABASE_KEY
      - key: ALLOWED_HOSTS
        value: "stars-n0np.onrender.com,*.render.com,*.onrender.com,127.0.0.1,localhost"
