# Generated by Django 5.2.8 on 2025-12-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_artwork_image_file_alter_artwork_image'),
        ('interactions', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='artwork_title_backup',
            field=models.CharField(blank=True, help_text='Backup of artwork title if deleted', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='gallery.artwork'),
        ),
    ]
