# Generated by Django 5.2.8 on 2025-12-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
