# Generated by Django 5.2.6 on 2025-09-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AddField(
            model_name='artwork',
            name='artId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favoriteId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='tagId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
