# Generated by Django 5.2.7 on 2025-10-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_badge_category_remove_favorite_artwork_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AddField(
            model_name='tag',
            name='tagId',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
