# Generated by Django 5.2.7 on 2025-10-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_tag_id_tag_tagid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tagId',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True),
        ),
    ]
