# Generated by Django 5.2.7 on 2025-10-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_tag_tagid_tag_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
